=== alexgcm97/IP-Assignment/xml/SalesOrder.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT SalesOrder (orderID, orderDate, shipDate, shipTime, shipMethod, to, product+, grandTotal )>
<!ELEMENT orderID (#PCDATA)>
<!ELEMENT orderDate (#PCDATA)>
<!ELEMENT shipDate (#PCDATA)>
<!ELEMENT shipTime (#PCDATA)>
<!ELEMENT shipMethod (#PCDATA)>
<!ELEMENT to (custName, custEmail, shipAddress)>
<!ELEMENT custName (#PCDATA)>
<!ELEMENT custEmail (#PCDATA)>
<!ELEMENT shipAddress (#PCDATA)>
<!ELEMENT product (no, name, description, price, quantity, totalAmount)>
<!ELEMENT no (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT totalAmount (#PCDATA)>
<!ELEMENT grandTotal (#PCDATA)>

=== alexgcm97/IP-Assignment/xml/SalesOrder.xml
<?xml version="1.0"?>
<!DOCTYPE SalesOrder SYSTEM "SalesOrder.dtd">
<?xml-stylesheet type="text/xsl" href="SalesOrder.xsl"?>
<SalesOrder>
  <orderID>1003</orderID>
  <orderDate>01 August 2018</orderDate>
  <shipDate>05 August 2018</shipDate>
  <shipTime>08:00 am</shipTime>
  <shipMethod>1</shipMethod>
  <to>
    <custName>Alex</custName>
    <custEmail>alex@gmail.com</custEmail>
    <shipAddress>-</shipAddress>
  </to>
  <product>
    <no>1</no>
    <name>Anemone</name>
    <description>1 unit, Monthly Sales</description>
    <price>3</price>
    <quantity>287</quantity>
    <totalAmount>861</totalAmount>
  </product>
  <grandTotal>861</grandTotal>
</SalesOrder>
